### PR TITLE
add options div, changed the look of jumbotron

### PR DESCRIPTION
**Pull request by aniarya82**
i tried adding the material design but the navigation bar has some problems. I manually changed the jumbotron looks to match to dat of material design. added the options tab

### CODE REVIEW

**Comment by icyflame** [comment]
@aniarya82 please remove the protocol ( http: ) from the link and script tag . 

When running on localhost using `python -m SimpleHTTPServer` using http will cause issues.

**Comment by aniarya82** [comment]
dat phython thing dint work :(

**Comment by icyflame** [comment]
maybe not on your machine! but generally it does, we will figure it out
next time we meet.

**Comment by aniarya82** [comment]
peace. fr time being let the https: stay, afterward we can remove it.

**Comment by icyflame** [comment]
No no, just remove it now, we need to follow some standards!

**Comment by aniarya82** [comment]
wht is this ISO certified or WHAT..????

**Comment by icyflame** [comment]
No! It's just a convention that many people on the internet follow, while
writing code!

**Comment by aniarya82** [comment]
yeah so not following it wont lead to any bad....!!!

**Comment by icyflame** [comment]
I started following this after seeing https://github.com/FezVrasta/bootstrap-material-design/pull/61 ! Professional people follow it!

**Comment by aniarya82** [comment]
WHAT DO WANT NOW everytime i pull i write https: first and while time of
push i remove.....!!!!!

**Comment by aniarya82** [comment]
Common man is sick for "FOLLOWING A CONVENTION"

**Comment by icyflame** [comment]
there's no need to write https.. without it also, the site will run just
fine, so there is no need to write it and then remove it later or something
like that!

**Comment by aniarya82** [comment]
Whatever :/

**Pull request merged**
