### PR TITLE
Changes to color scheme. Text and background added. Landing section enhancement.

### PR DESCRIPTION
**Pull request by mrahul17**
Now, the only work remaining is to add images. I think you people can do that on your own. I'll send you the pics.

### CODE REVIEW

**Comment by icyflame** [comment]
Hall president section is still slightly buggy.

Imgur

Can something be done to fix this? Should we reduce the number of images in one row? I think that will help.

**Comment by icyflame** [comment]
Also @light94 , And the images of all the committee members are of different sizes, this gives the page a misplaced assymetric look. I think we should crop all the images to the same (square) dimensions and then upload it?

**Comment by mrahul17** [comment]
yes, that has to be done.

http://www.alumnimeet.iitkgp.ernet.in/home.php

_R__ahul Mishra_

Coordinator | Students' Alumni Cell

Office Of Alumni Affairs and

International Relations | IIT Kharagpur http://www.iitkgp.ac.in/

+91 8967754451 | mishra.rahul1712@gmail.com
Facebook https://www.facebook.com/iitkgp.alumnicell | Linkedin
https://www.linkedin.com/groups?home=&gid=2803&trk=groups_item_detail-h-logo
 | Twitter https://twitter.com/alumni_iitkgp | Quora
http://www.quora.com/Student-Alumni-Cell-Iit-Kharagpur

**Comment by icyflame** [comment]
@light94 And you removed the slider that was there in the landing section?

**Comment by mrahul17** [comment]
Yes, i did. the new picture conveys what we actually wanted.

http://www.alumnimeet.iitkgp.ernet.in/home.php

_R__ahul Mishra_

Coordinator | Students' Alumni Cell

Office Of Alumni Affairs and

International Relations | IIT Kharagpur http://www.iitkgp.ac.in/

+91 8967754451 | mishra.rahul1712@gmail.com
Facebook https://www.facebook.com/iitkgp.alumnicell | Linkedin
https://www.linkedin.com/groups?home=&gid=2803&trk=groups_item_detail-h-logo
 | Twitter https://twitter.com/alumni_iitkgp | Quora
http://www.quora.com/Student-Alumni-Cell-Iit-Kharagpur

**Comment by mrahul17** [comment]
the  bug in the hp panel has been removed, only the badge markup was missing.

**Pull request merged**
